import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "../components/Theme-provider";
import Navbar from "../components/Navbar/Navbar";
import SessionWrapper from "../components/SessionWrapper";
import ChatPage from "../components/PrivateChat";
import PrivateChat from "../components/PrivateChat";
import FloatingChatWrapper from "../components/PrivateChat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionWrapper>
            <Navbar />
            <Toaster position="top-center" />
            {children}
            <FloatingChatWrapper /> {/* ลอยแบบ Facebook + แก้ error */}
          </SessionWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
